### ISSUE TITLE
Can't compile ESP32

### ISSUE THREAD

**Issue by ellogwen** [jostlowe/Pico-DMX#10]
According to Platform.IO this library should work with Espressif32 platform. However, I am missing headers dma.h

```
In file included from src\main.cpp:28:0:
.pio\libdeps\esp32dev\Pico-DMX\src/DmxOutput.h:10:17: fatal error: dma.h: No such file or directory
```

Any Idea, where I can get them?

**Comment by jostlowe** [comment]
Hi!

For some reason, PlatformIO shows that this library is supported by all platforms. Pico-DMX only runs on the Raspberry Pi Pico and not other platforms, as it uses some dedicated hardware on the RP2040 chip that the Raspberry Pi Pico runs on. That's why it shows missing header files. I'll see if i can't update the library information so it displays correctly on PlatformIO
